### ISSUE TITLE
New Relic notification channels no longer support `SLACK` type

### ISSUE THREAD

**Issue by bbraunstein** [newrelic/newrelic-k8s-operator-v2#20]
## Version

Chart version `1.3.0`

## What steps will reproduce the bug?

1. Create `alertworkflow.yaml` with a `SLACK` notification channel:

  ```yaml
  apiVersion: alerts.k8s.newrelic.com/v1
  kind: AlertWorkflow
  metadata:
    name: nr-alert-workflow
  spec:
    accountId: 1234567
    apiKeySecret:
      name: new-relic-api-key
      namespace: new-relic-k8s-operator-system
      keyName: api-key
    region: "US"
    name: "nr-alert-workflow"
    enabled: true
    issuesFilter:
      name: test-filter
      type: "FILTER"
      predicates:
        - attribute: accumulations.policyName
          operator: "EXACTLY_MATCHES"
          values:
            - "nr-alert-policy"
    mutingRulesHandling: "DONT_NOTIFY_FULLY_OR_PARTIALLY_MUTED_ISSUES"
    channels:
      - notificationTriggers:
          - "ACTIVATED"
          - "ACKNOWLEDGED"
          - "CLOSED"
          - "PRIORITY_CHANGED"
          - "OTHER_UPDATES"
        spec:
          name: "#my-slack-channel"
          destinationName: "My Global Slack Destination"
          product: "IINT"
          properties:
            - key: "channelId"
              value: "ABCDEFGH"
          type: "SLACK"
  ```
2. Apply the YAML: `kubectl apply -f alertworkflow.yaml`
  
## What is the expected behavior?

The `AlertWorkflow` is created with a notification channel of type `SLACK`.

## What do you see instead?

```
AlertWorkflow/new-relic-k8s-operator-system/nr-alert-workflow dry-run failed (Invalid): admission webhook "valertworkflow.kb.io" denied the request: AlertWorkflow.alerts.k8s.newrelic.com "nr-alert-workflow" is invalid: spec.type: Invalid value: "SLACK": invalid channel type - must be one of: EMAIL | EVENT_BRIDGE | JIRA | MOBILE_PUSH | PAGERDUTY_SERVICE_INTEGRATION | PAGERDUTY_ACCOUNT_INTEGRATION | SERVICE_NOW_APP | WEBHOOK
```

## Additional information

- Issue does not appear in prior Helm Chart version `0.3.0`
- New Relic's [Terraform provider](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel) shows `SLACK` as a valid type for notification channels
